### ISSUE TITLE
Does mongo feature merge to official flyway version

### ISSUE THREAD

**Issue by fgcui1204** [risksense/flyway#11]
Hello Ristsense,

  Thanks for your work to support mongo. I found your code haven't merge to [official version](https://github.com/flyway/flyway). Is any plan to do that?

**Comment by MMJM** [comment]
Would love to know the progress on the merge with the official version?

**Comment by khatkar** [comment]
@fgcui1204 @MMJM We created a pull request with the official repo, and the flyway community has to approve and merge it. We do not have any control over when it will happen.

Also, please do not put these questions as *issue* on Github.
